apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app: redis
    tier: backend
    role: follower
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    tier: backend
    role: follower
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-follower
spec:
  selector:
    matchLabels:
      app: redis
      role: follower
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: follower
        tier: backend
    spec:
      containers:
        - name: follower
          image: us-docker.pkg.dev/google-samples/containers/gke/gb-redis-follower:v2
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
